### PR TITLE
Modbus plugin for VEM PLC.

### PR DESCRIPTION
**Pull request by MatthewHink**
This is working for the VEM PLC. I think 1.1.0 is the correct base to merge to.

### CODE REVIEW

**Comment by edaniszewski** [comment]
This also brings up conversions.. other plugins may also need to use some standard conversions (e.g., deg. C <-> deg. F), so we may eventually want to add a `conversions` package to the SDK. We could also add a conversion field to the output type so we can just reference it by name and wouldn't need any code changes. Wouldn't be done in the near term, but just a thought

**Comment by MatthewHink** [comment]
------
Agree on the conversions. Sooner or later the SDK should do that. 

------
As far as built in types, is that a reference to the output types? I get that. Another option is to put them in yaml only, which adds complexity.

------
An issue on scan versus reading types:

Scan:```
            {
              "id":"5b651529b719e68f68ebd2e8c5efdb37",
              "info":"Active Flow Setpoint",
              "type":"flow"
            },
```

Reading:
```
vapor@basx-vec1:~/src/deployment/site/oregon/redmond$ curl http://${SYNSE_IP}:5000/synse/v2/read/vem-rack/vem-plc/5b651529b719e68f68ebd2e8c5efdb37
{
  "kind":"vem-plc.active.flow",
  "data":[
    {
      "value":800,
      "timestamp":"2018-10-19T14:45:43.167631692Z",
      "unit":{
        "symbol":"gpm",
        "name":"gallons per minute"
      },
      "type":"flowGpm",
      "info":"Active Flow Setpoint"
    }
  ]
}```

The type flowGpm on the reading is combining the OutputType units with the reading type (could be just flow).
One option would be to create an OutputType member DisplayName, here set to "flow". We currently need two different flow outputs due to scaling, and one has to have a different name than the other.

------
Another issue is that the parallel / serial polling is plugin specific and not device specific. The VEM PLC will easily get overwhelmed in parallel after 10-20 sensors are added. This may not be true with other devices. This is just optimization however. We need it to functionally work first.

**Comment by MatthewHink** [comment]
It's probably because the english to metric conversion is happening prior to the scaling factor.

**Comment by MatthewHink** [comment]
Okay so I have removed the english to metric conversion. There is another issue. We lose the decimal with the SDK Scaling Factor:

I do a raw reading on HRC Mixed Fluid Temperature with pcli. I get:

```
vapor@basx-vec1:~/go/src/github.com/vapor-ware/synse-plugins-internal/pcli$ PLC_IP=10.193.4.250:502
vapor@basx-vec1:~/go/src/github.com/vapor-ware/synse-plugins-internal/pcli$ sudo -HE env PATH=$PATH build/pcli mip ${PLC_IP} get holding 1
DEBU[0000] readHoldingRegister 0x0001, decimal 1
INFO[0002] 464 0x1d0
```

This reading is 464 decimal which in this case is 46.4 degrees F

I do the reading via synse:

```
vapor@basx-vec1:~/src/deployment/site/oregon/redmond$ curl http://${SYNSE_IP}:5000/synse/v2/read/vem-rack/vem-plc/3e0ceb7d981857ed0316b19422da9e55
{
  "kind":"vem-plc.hrc.mixed.fluid.temperature",
  "data":[
    {
      "value":46,
      "timestamp":"2018-10-19T15:50:47.908281426Z",
      "unit":{
        "symbol":"F",
        "name":"fahrenheit"
      },
      "type":"temperatureFTenths",
      "info":"HRC Mixed Fluid Temperature"
    }
  ]
}
```

Issue is that the Synse ScalingFactor loses the decimal. We should get 46.4 and not 46.

**Comment by MatthewHink** [comment]
Added second commit to remove english to metric conversions for now until we are ready.

**Comment by edaniszewski** [comment]
thanks for all the good feedback and reporting on sdk stuff. I opened some issues in the SDK repo to begin tracking. I'll work on the scaling factor bug shortly. 

one thing I need to look into is regarding your comment on this bit:
> The type flowGpm on the reading is combining the OutputType units with the reading type (could be just flow). 
> One option would be to create an OutputType member DisplayName, here set to "flow". We currently need two different flow outputs due to scaling, and one has to have a different name than the other.

I know that we do namespacing at various levels where the final component contains the type info -- e.g. the device kind `vem-plc.hrc.mixed.fluid.temperature` has the terminal component `temperature` which describes the device type. I'll need to double check in the docs, but that may also be the case with the output type names (e.g. instead of `flowGpm` it could be named `gpm.flow` and then be given the "flow" type).

Adding a DisplayName member could still be a good route to take, or at the very least providing an explicit way to define the actual type instead of implicitly within the namespace.

**Comment by MatthewHink** [comment]
The config part for flow, which you have not seen yet, is currently here:

https://github.com/vapor-ware/deployment/blob/mhink-bx/site/oregon/redmond/values.yaml#L269-L286

The namespacing is happening on the scan, so we get type flow. It's using the OutputType type on the reading, so we get flowGpm.

```
      # Active Flow Setpoint.
      - name: vem-plc.active.flow
        instances:
          - info: Active Flow Setpoint
            location : vem-location
            handlerName: holding_register
            data:
              host: 10.193.4.250
              port: 502
              timeout: 10s
              failOnError: false
            outputs:
              - type: flowGpm
                info: Active Flow Setpoint
                data:
                  address: 0x2D # 45 decimal
                  width: 1
                  type: u16
```

**Comment by MatthewHink** [comment]
I guess another way of doing it would be to make the output type Gpm.flow, but then it's also just more cryptic (but consistent) namespacing.

**Comment by edaniszewski** [comment]
The output type name can be namespaced:

https://github.com/vapor-ware/synse-sdk/blob/928f440f86af86daddd765388cb249884612722c/sdk/type.go#L19-L22

and there is a helper to get the type via the namespace 

https://github.com/vapor-ware/synse-sdk/blob/928f440f86af86daddd765388cb249884612722c/sdk/type.go#L65-L74

**Pull request merged**
